<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.getcwd()

'/content'

In [3]:
os.chdir("/content/drive/MyDrive/CDAC")

In [4]:
df = pd.read_excel("CDAC_DataBook.xlsx",sheet_name='ERPData')
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [5]:
grp1 = df.groupby(df.MaterialID)
grp1.get_group('SDRT-67')

   MaterialID Location  Quantity
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31

In [6]:
print(grp1.Quantity.agg(np.sum),end='\n\n')
print(grp1.Quantity.agg('sum'),end='\n\n')

MaterialID
AXCP-78    898
DDBN-89    383
GCVB-79    182
LXCV-21    243
SDRT-67    294
TMI-43T    885
Name: Quantity, dtype: int64

MaterialID
AXCP-78    898
DDBN-89    383
GCVB-79    182
LXCV-21    243
SDRT-67    294
TMI-43T    885
Name: Quantity, dtype: int64

/tmp/ipykernel_8610/1289200661.py:1: FutureWarning: The provided callable <function sum at 0x7e73d4734860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  print(grp1.Quantity.agg(np.sum),end='\n\n')

In [7]:
grp1 = df.groupby(['Location','MaterialID'])
grp1.groups

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [8]:
grp1.Quantity.agg('sum')

Location  MaterialID
MWH-1     AXCP-78       548
          DDBN-89       130
          SDRT-67        91
          TMI-43T       120
MWH-2     AXCP-78        85
          DDBN-89        69
          GCVB-79       156
          LXCV-21        27
          SDRT-67        31
          TMI-43T        29
MWH-3     AXCP-78        29
          DDBN-89        38
          LXCV-21        42
          TMI-43T        65
MWH-4     AXCP-78        36
          DDBN-89        75
          SDRT-67        58
          TMI-43T       559
MWH-5     AXCP-78       200
          DDBN-89        71
          GCVB-79        26
          LXCV-21       174
          SDRT-67       114
          TMI-43T       112
Name: Quantity, dtype: int64

In [9]:
ind = np.where((df.Location=='MWH-1')&(df.MaterialID=='AXCP-78'))
df.iloc[ind].Quantity.sum()

np.int64(548)

In [10]:
newdf = grp1.agg([np.sum,np.mean,np.size])
newdf

/tmp/ipykernel_8610/2861715478.py:1: FutureWarning: The provided callable <function sum at 0x7e73d4734860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  newdf = grp1.agg([np.sum,np.mean,np.size])
/tmp/ipykernel_8610/2861715478.py:1: FutureWarning: The provided callable <function mean at 0x7e73d4735940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  newdf = grp1.agg([np.sum,np.mean,np.size])

                    Quantity
                         sum        mean size
Location MaterialID
MWH-1    AXCP-78         548  109.600000    5
         DDBN-89         130   43.333333    3
         SDRT-67          91   45.500000    2
         TMI-43T         120  120.000000    1
MWH-2    AXCP-78          85   85.000000    1
         DDBN-89          69   69.000000    1
         GCVB-79         156   39.000000    4
         LXCV-21          27   27.000000    1
         SDRT-67          31   31.000000    1
         TMI-43T          29   29.000000    1
MWH-3    AXCP-78          29   29.000000    1
         DDBN-89          38   38.000000    1
         LXCV-21          42   42.000000    1
         TMI-43T          65   65.000000    1
MWH-4    AXCP-78          36   36.000000    1
         DDBN-89          75   37.500000    2
         SDRT-67          58   58.000000    1
         TMI-43T         559   50.818182   11
MWH-5    AXCP-78         200   66.666667    3
         DDBN-89          71   71.000000    1
         GCVB-79          26   26.000000    1
         LXCV-21         174   58.000000    3
         SDRT-67         114   57.000000    2
         TMI-43T         112  112.000000    1

In [11]:
newdf.loc['MWH-1']

           Quantity
                sum        mean size
MaterialID
AXCP-78         548  109.600000    5
DDBN-89         130   43.333333    3
SDRT-67          91   45.500000    2
TMI-43T         120  120.000000    1

In [12]:
newdf.loc[['MWH-1','MWH-2']]

                    Quantity
                         sum        mean size
Location MaterialID
MWH-1    AXCP-78         548  109.600000    5
         DDBN-89         130   43.333333    3
         SDRT-67          91   45.500000    2
         TMI-43T         120  120.000000    1
MWH-2    AXCP-78          85   85.000000    1
         DDBN-89          69   69.000000    1
         GCVB-79         156   39.000000    4
         LXCV-21          27   27.000000    1
         SDRT-67          31   31.000000    1
         TMI-43T          29   29.000000    1

Sorting of DataFrame

In [13]:
df_sorted = df.sort_values('Quantity')
print(df_sorted.head(),end='\n\n')
print(df_sorted.tail(),end='\n\n')

   MaterialID Location  Quantity
8     GCVB-79    MWH-2        10
16    SDRT-67    MWH-5        12
34    GCVB-79    MWH-5        26
30    DDBN-89    MWH-4        27
2     LXCV-21    MWH-2        27

   MaterialID Location  Quantity
25    AXCP-78    MWH-1       109
33    TMI-43T    MWH-5       112
9     TMI-43T    MWH-1       120
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152

In [14]:
df_sorted = df.sort_values('Quantity',ascending=False)
df_sorted

   MaterialID Location  Quantity
24    AXCP-78    MWH-1       152
39    AXCP-78    MWH-1       145
9     TMI-43T    MWH-1       120
33    TMI-43T    MWH-5       112
25    AXCP-78    MWH-1       109
17    SDRT-67    MWH-5       102
15    GCVB-79    MWH-2        87
46    AXCP-78    MWH-2        85
27    LXCV-21    MWH-5        83
5     TMI-43T    MWH-4        78
12    TMI-43T    MWH-4        76
21    TMI-43T    MWH-4        75
48    AXCP-78    MWH-1        75
23    DDBN-89    MWH-5        71
38    AXCP-78    MWH-5        70
45    DDBN-89    MWH-2        69
1     AXCP-78    MWH-1        67
3     AXCP-78    MWH-5        65
31    TMI-43T    MWH-4        65
37    AXCP-78    MWH-5        65
14    TMI-43T    MWH-3        65
11    SDRT-67    MWH-4        58
29    LXCV-21    MWH-5        57
41    SDRT-67    MWH-1        57
26    DDBN-89    MWH-1        57
19    TMI-43T    MWH-4        52
22    DDBN-89    MWH-4        48
32    TMI-43T    MWH-4        43
44    LXCV-21    MWH-3        42
49    DDBN-89    MWH-1        39
20    TMI-43T    MWH-4        39
43    DDBN-89    MWH-3        38
4     AXCP-78    MWH-4        36
0     TMI-43T    MWH-4        34
40    DDBN-89    MWH-1        34
28    LXCV-21    MWH-5        34
10    SDRT-67    MWH-1        34
18    TMI-43T    MWH-4        34
13    TMI-43T    MWH-4        32
6     TMI-43T    MWH-4        31
42    SDRT-67    MWH-2        31
35    GCVB-79    MWH-2        31
47    AXCP-78    MWH-3        29
7     TMI-43T    MWH-2        29
36    GCVB-79    MWH-2        28
2     LXCV-21    MWH-2        27
30    DDBN-89    MWH-4        27
34    GCVB-79    MWH-5        26
16    SDRT-67    MWH-5        12
8     GCVB-79    MWH-2        10

In [15]:
df_sorted = df.sort_values(['MaterialID','Location','Quantity'])
df_sorted

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
48    AXCP-78    MWH-1        75
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
4     AXCP-78    MWH-4        36
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
40    DDBN-89    MWH-1        34
49    DDBN-89    MWH-1        39
26    DDBN-89    MWH-1        57
45    DDBN-89    MWH-2        69
43    DDBN-89    MWH-3        38
30    DDBN-89    MWH-4        27
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
8     GCVB-79    MWH-2        10
36    GCVB-79    MWH-2        28
35    GCVB-79    MWH-2        31
15    GCVB-79    MWH-2        87
34    GCVB-79    MWH-5        26
2     LXCV-21    MWH-2        27
44    LXCV-21    MWH-3        42
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
27    LXCV-21    MWH-5        83
10    SDRT-67    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
11    SDRT-67    MWH-4        58
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
9     TMI-43T    MWH-1       120
7     TMI-43T    MWH-2        29
14    TMI-43T    MWH-3        65
6     TMI-43T    MWH-4        31
13    TMI-43T    MWH-4        32
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
20    TMI-43T    MWH-4        39
32    TMI-43T    MWH-4        43
19    TMI-43T    MWH-4        52
31    TMI-43T    MWH-4        65
21    TMI-43T    MWH-4        75
12    TMI-43T    MWH-4        76
5     TMI-43T    MWH-4        78
33    TMI-43T    MWH-5       112

In [16]:
df_sorted = df.sort_values(['MaterialID','Location','Quantity'],ascending=[True,False,True])
df_sorted

   MaterialID Location  Quantity
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
4     AXCP-78    MWH-4        36
47    AXCP-78    MWH-3        29
46    AXCP-78    MWH-2        85
1     AXCP-78    MWH-1        67
48    AXCP-78    MWH-1        75
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152
23    DDBN-89    MWH-5        71
30    DDBN-89    MWH-4        27
22    DDBN-89    MWH-4        48
43    DDBN-89    MWH-3        38
45    DDBN-89    MWH-2        69
40    DDBN-89    MWH-1        34
49    DDBN-89    MWH-1        39
26    DDBN-89    MWH-1        57
34    GCVB-79    MWH-5        26
8     GCVB-79    MWH-2        10
36    GCVB-79    MWH-2        28
35    GCVB-79    MWH-2        31
15    GCVB-79    MWH-2        87
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
27    LXCV-21    MWH-5        83
44    LXCV-21    MWH-3        42
2     LXCV-21    MWH-2        27
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
11    SDRT-67    MWH-4        58
42    SDRT-67    MWH-2        31
10    SDRT-67    MWH-1        34
41    SDRT-67    MWH-1        57
33    TMI-43T    MWH-5       112
6     TMI-43T    MWH-4        31
13    TMI-43T    MWH-4        32
0     TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        34
20    TMI-43T    MWH-4        39
32    TMI-43T    MWH-4        43
19    TMI-43T    MWH-4        52
31    TMI-43T    MWH-4        65
21    TMI-43T    MWH-4        75
12    TMI-43T    MWH-4        76
5     TMI-43T    MWH-4        78
14    TMI-43T    MWH-3        65
7     TMI-43T    MWH-2        29
9     TMI-43T    MWH-1       120

Merging DataFrame

In [17]:
mumbai = pd.read_excel("CDAC_DataBook.xlsx",sheet_name='Mumbai')
pune = pd.read_excel("CDAC_DataBook.xlsx",sheet_name='Pune')

In [18]:
mumbai

       Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B
5     Vinod          AI     C

In [19]:
pune

      Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B
5    Vinod           AI     B

In [20]:
pd.merge(pune,mumbai)   # it will show empty df because there is no common row between two dfs

Empty DataFrame
Columns: [Name, Subject, Grade]
Index: []

In [21]:
pd.merge(pune,mumbai,on='Subject')

    Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A
4    Vinod          AI       B     Vinod       C

In [22]:
pd.merge(pune,mumbai,on=['Subject','Grade'])

    Name_x     Subject Grade   Name_y
0   Rakesh      Python     A   Chetan
1  Vaibhav  Statistics     B  Deepika
2   Hitesh  CommSkills     A    Arjun

In [23]:
# inner join
pd.merge(pune,mumbai,on='Subject',how='inner')

    Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A
4    Vinod          AI       B     Vinod       C

In [24]:
# outer join
pd.merge(pune,mumbai,on='Subject',how='outer')

    Name_x      Subject Grade_x    Name_y Grade_y
0    Vinod           AI       B     Vinod       C
1   Hitesh   CommSkills       A     Arjun       A
2    Manoj     MLPython       C  Abhishek       B
3   Suyash  ProjectMgmt       B       NaN     NaN
4   Rakesh       Python       A    Chetan       A
5      NaN    Six Sigma     NaN   Vaibhav       A
6  Vaibhav   Statistics       B   Deepika       B

In [25]:
# left join
pd.merge(pune,mumbai,on='Subject',how='left')

    Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN
5    Vinod           AI       B     Vinod       C

In [26]:
# right join
pd.merge(pune,mumbai,on='Subject',how='right')

    Name_x     Subject Grade_x    Name_y Grade_y
0      NaN   Six Sigma     NaN   Vaibhav       A
1  Vaibhav  Statistics       B   Deepika       B
2   Hitesh  CommSkills       A     Arjun       A
3   Rakesh      Python       A    Chetan       A
4    Manoj    MLPython       C  Abhishek       B
5    Vinod          AI       B     Vinod       C

In [27]:
pd.merge(pune,mumbai,on=['Subject','Grade'],how='outer')

    Name_x      Subject Grade    Name_y
0    Vinod           AI     B       NaN
1      NaN           AI     C     Vinod
2   Hitesh   CommSkills     A     Arjun
3      NaN     MLPython     B  Abhishek
4    Manoj     MLPython     C       NaN
5   Suyash  ProjectMgmt     B       NaN
6   Rakesh       Python     A    Chetan
7      NaN    Six Sigma     A   Vaibhav
8  Vaibhav   Statistics     B   Deepika

**Practice Question**

First worksheet gives the student ID and the course for which he has enrolled. the second sheet gives the student ID and the marks they get after the final exam.

Who are students who have enrolled but not given the exam.

In [28]:
os.getcwd()

'/content/drive/MyDrive/CDAC'

In [31]:
df1 = pd.read_excel("institute.xlsx",sheet_name='Enrollment')
df2 = pd.read_excel("institute.xlsx",sheet_name='Exam')

In [32]:
df1

  StuID       Subject
0  S101        Python
1  S103            AI
2  S104   DataScience
3  S107  MLWithPython
4  S109            AI
5  S105   DataScience
6  S108   DataScience

In [33]:
df2

  StuID  Marks
0  S101     80
1  S105     68
2  S104     49
3  S102     62
4  S103     68
5  S107     70

In [36]:
result = pd.merge(df1,df2,on='StuID',how='left')
result

  StuID       Subject  Marks
0  S101        Python   80.0
1  S103            AI   68.0
2  S104   DataScience   49.0
3  S107  MLWithPython   70.0
4  S109            AI    NaN
5  S105   DataScience   68.0
6  S108   DataScience    NaN

In [39]:
result.iloc[np.where(result.Marks.isnull())].reset_index(drop=True)

  StuID      Subject  Marks
0  S109           AI    NaN
1  S108  DataScience    NaN