<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [126]:
import numpy as np
import pandas as pd

In [127]:
# Set
a1 = np.array([3,7,6,1,8,9])
a2 = np.array([2,4,5,8,10,3,6])
a1 , a2

(array([3, 7, 6, 1, 8, 9]), array([ 2,  4,  5,  8, 10,  3,  6]))

In [128]:
# | (+) -> union1d() -- either in set one or set 2
np.union1d(a1,a2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
# & (*) -> intersect1d() -- common to set 1 and set 2
np.intersect1d(a1,a2)

array([3, 6, 8])

In [130]:
#np.in1d(a1,a2)    #/tmp/ipykernel_10826/1595240845.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.np.in1d(a1,a2)
np.isin(a1,a2)

array([ True, False,  True, False,  True, False])

In [131]:
# setdiff1d()
np.setdiff1d(a1,a2)

array([1, 7, 9])

In [132]:
np.setdiff1d(a2,a1)

array([ 2,  4,  5, 10])

In [133]:
# setxor1d() - union of unique element      # symmetric_difference -> {3, 7, 6, 1, 8, 9}.symmetric_difference({2,  4,  5,  8, 10,  3,  6}) = {1, 2, 4, 5, 7, 9, 10}
np.setxor1d(a1,a2)

array([ 1,  2,  4,  5,  7,  9, 10])

In [134]:
# Vectors
x1 = np.array([2,3,-4])
x2 = np.array([3,-2,1])
x1,x2

(array([ 2,  3, -4]), array([ 3, -2,  1]))

In [135]:
# dot() -> dot product of 2 vectors
# Note : when dot product of 2 vectors is 0 then 2 vecotrs are perpendicular to each other
np.dot(x1,x2)

np.int64(-4)

In [136]:
# determinant -> linalg.det()
from numpy import linalg

x3 = np.array([[1,2,3],[0,1,2],[1,1,0]])
np.linalg.det(x3)

np.float64(-1.0)

In [137]:
# cross() -> cross product of 2 vecctors
np.cross(x1,x2)

array([ -5, -14, -13])

In [138]:
# random module
from numpy import random
print(np.random.rand(10))   # 10 random no. between 0 and 1
print(np.random.randint(5,15))  # any random no. between 5 and 15
print(np.random.randint(5,50,15))  # 15 random no. between 5 and 50
np.random.randn(5)

[0.82096474 0.11703323 0.10521269 0.34565417 0.91918696 0.19500821
 0.54829108 0.22384952 0.24085789 0.18631526]
6
[ 8 17 22 17 49 33 40 13 13 43 44 42  7 10 41]

array([-0.14469098,  1.46643922, -0.79676157, -0.20210375, -0.99270264])

# **Pandas**

# Series

In [139]:
import pandas as pd

In [140]:
# series creation
x1 = [4,8,4,3,2]
x1 = pd.Series(x1)
x1

0    4
1    8
2    4
3    3
4    2
dtype: int64

In [141]:
# labeling series
x1 = [4,8,4,3,2]
s1 = pd.Series(x1, index = ['I','II','III','IV','V'])
s1

I      4
II     8
III    4
IV     3
V      2
dtype: int64

In [142]:
# index based extraction
s1.iloc[2]

np.int64(4)

In [143]:
# label based extraction
s1.loc['III']

np.int64(4)

In [144]:
print(s1)
print(s1.iloc[[1,3]])   # index based extraction of multiple values
print(s1.loc[['II','IV']])  # label based extraction of multiple values

I      4
II     8
III    4
IV     3
V      2
dtype: int64
II    8
IV    3
dtype: int64
II    8
IV    3
dtype: int64

In [145]:
# labeling can contain duplicate labels
s2 = pd.Series([1,2,3,4,5],index=['A','A','B','A','B'])
print(s2,end="\n\n")

print(s2.iloc[3],end="\n\n")

print(s2.loc['A'],end="\n\n")

print(s2.loc[['A','B']])

A    1
A    2
B    3
A    4
B    5
dtype: int64

4

A    1
A    2
A    4
dtype: int64

A    1
A    2
A    4
B    3
B    5
dtype: int64

In [146]:
# merging or concatinating two series
print(s1,end="\n\n")

s3 = pd.Series([3,9],index=['VI',"VII"])
print(s3,end="\n\n")

s1 = pd.concat([s1,s3])
print(s1)
len(s1)

I      4
II     8
III    4
IV     3
V      2
dtype: int64

VI     3
VII    9
dtype: int64

I      4
II     8
III    4
IV     3
V      2
VI     3
VII    9
dtype: int64

7

In [147]:
print(s1.iloc[4])
s1.iloc[4]=9          # modify value based on index
print(s1,end="\n\n")

print(s1.loc['V'])
s1.loc['V']=11        # modify value based on label
print(s1)

2
I      4
II     8
III    4
IV     3
V      9
VI     3
VII    9
dtype: int64

9
I       4
II      8
III     4
IV      3
V      11
VI      3
VII     9
dtype: int64

In [148]:
# modification on duplicate labels
print(s2,end='\n\n')
s2.loc['A']=4
print(s2,end='\n\n')
s2.iloc[1]=8
print(s2,end='\n\n')

A    1
A    2
B    3
A    4
B    5
dtype: int64

A    4
A    4
B    3
A    4
B    5
dtype: int64

A    4
A    8
B    3
A    4
B    5
dtype: int64

In [149]:
# deleting values from series with help of labels
s1 = s1.drop(['V'])         # droped vale at label V
print(s1,end='\n\n')
s1 = s1.drop(['VI','VII'])  # droped value with multiple label
print(s1,end='\n\n')

I      4
II     8
III    4
IV     3
VI     3
VII    9
dtype: int64

I      4
II     8
III    4
IV     3
dtype: int64

In [150]:
# deleting values from series with help of index
print(s1,end='\n\n')
print(s1.drop(s1.index[2]))
print(s1,end='\n\n')
print(s1.drop(s1.index[[1,2]]))
print(s1,end='\n\n')

I      4
II     8
III    4
IV     3
dtype: int64

I     4
II    8
IV    3
dtype: int64
I      4
II     8
III    4
IV     3
dtype: int64

I     4
IV    3
dtype: int64
I      4
II     8
III    4
IV     3
dtype: int64

In [151]:
s4 = pd.Series([2,3,2,2,4,4,3,4,4,4,5,5,2,4,5])
s5=s4.value_counts()    # counts the count of number and will display in descending order of values
print(s5,end='\n\n')
print(s5.loc[2],end='\n\n')
print(s5.iloc[2],end='\n\n')

4    6
2    4
5    3
3    2
Name: count, dtype: int64

4

3

In [152]:
# if we dont know index and label just know values
print(s1)

print(np.where(s1==8))

print(s1.index[np.where(s1==8)[0]])

print(s1.index)

s1.iloc[np.where(s1==4)[0]]=1
s1.loc[s1.index[np.where(s1==8)[0]]]=10
s1.loc[s1.index[np.where(s1==3)]]=10
print(s1)

I      4
II     8
III    4
IV     3
dtype: int64
(array([1]),)
Index(['II'], dtype='object')
Index(['I', 'II', 'III', 'IV'], dtype='object')
I       1
II     10
III     1
IV     10
dtype: int64

# DataFrame

In [153]:
# DataFrame Creation

mydata = [['A',1234,20000],['B',5678,10000],['C',1357,8000],['D',4567,30000]]
print(len(mydata),end='\n\n')
print(len(mydata[0]),end='\n\n')

mydf = pd.DataFrame(mydata)
print(mydf,end='\n\n')

mydf = pd.DataFrame(mydata,columns=['Name','AccNo','Balance'])
print(mydf,end='\n\n')

temp = pd.DataFrame(mydata,columns=['Name','AccNo','Balance'],index=['Sujal','Chaitu','Omkie','Deva'])
print(temp,end='\n\n')

4

3

   0     1      2
0  A  1234  20000
1  B  5678  10000
2  C  1357   8000
3  D  4567  30000

  Name  AccNo  Balance
0    A   1234    20000
1    B   5678    10000
2    C   1357     8000
3    D   4567    30000

       Name  AccNo  Balance
Sujal     A   1234    20000
Chaitu    B   5678    10000
Omkie     C   1357     8000
Deva      D   4567    30000

In [156]:
print(mydf,end='\n\n')

print(mydf.iloc[[1,2]],end='\n\n')

print(mydf.loc[[1,2]],end='\n\n')

df1 = mydf.iloc[[1,2]]                        # it carry forwards the same label
print(df1,end='\n\n')
print(df1.iloc[1],end='\n\n')
print(df1.loc[1],end='\n\n')

df1 = mydf.iloc[[1,2]].reset_index(drop=True) # it will not carry forward the same label
print(df1,end='\n\n')

df1 = mydf.iloc[[1,2]].reset_index()  # if we dont mention drop=True then index column will be added
print(df1,end='\n\n')

  Name  AccNo  Balance
0    A   1234    20000
1    B   5678    10000
2    C   1357     8000
3    D   4567    30000

  Name  AccNo  Balance
1    B   5678    10000
2    C   1357     8000

  Name  AccNo  Balance
1    B   5678    10000
2    C   1357     8000

  Name  AccNo  Balance
1    B   5678    10000
2    C   1357     8000

Name          C
AccNo      1357
Balance    8000
Name: 2, dtype: object

Name           B
AccNo       5678
Balance    10000
Name: 1, dtype: object

  Name  AccNo  Balance
0    B   5678    10000
1    C   1357     8000

   index Name  AccNo  Balance
0      1    B   5678    10000
1      2    C   1357     8000