<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
# Set
a1 = np.array([3,7,6,1,8,9])
a2 = np.array([2,4,5,8,10,3,6])
a1 , a2

(array([3, 7, 6, 1, 8, 9]), array([ 2,  4,  5,  8, 10,  3,  6]))

In [5]:
# | (+) -> union1d() -- either in set one or set 2
np.union1d(a1,a2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# & (*) -> intersect1d() -- common to set 1 and set 2
np.intersect1d(a1,a2)

array([3, 6, 8])

In [7]:
#np.in1d(a1,a2)    #/tmp/ipykernel_10826/1595240845.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.np.in1d(a1,a2)
np.isin(a1,a2)

array([ True, False,  True, False,  True, False])

In [8]:
# setdiff1d()
np.setdiff1d(a1,a2)

array([1, 7, 9])

In [9]:
np.setdiff1d(a2,a1)

array([ 2,  4,  5, 10])

In [10]:
# setxor1d() - union of unique element      # symmetric_difference -> {3, 7, 6, 1, 8, 9}.symmetric_difference({2,  4,  5,  8, 10,  3,  6}) = {1, 2, 4, 5, 7, 9, 10}
np.setxor1d(a1,a2)

array([ 1,  2,  4,  5,  7,  9, 10])

In [11]:
# Vectors
x1 = np.array([2,3,-4])
x2 = np.array([3,-2,1])
x1,x2

(array([ 2,  3, -4]), array([ 3, -2,  1]))

In [12]:
# dot() -> dot product of 2 vectors
# Note : when dot product of 2 vectors is 0 then 2 vecotrs are perpendicular to each other
np.dot(x1,x2)

np.int64(-4)

In [13]:
# determinant -> linalg.det()
from numpy import linalg

x3 = np.array([[1,2,3],[0,1,2],[1,1,0]])
np.linalg.det(x3)

np.float64(-1.0)

In [14]:
# cross() -> cross product of 2 vecctors
np.cross(x1,x2)

array([ -5, -14, -13])

In [15]:
# random module
from numpy import random
print(np.random.rand(10))   # 10 random no. between 0 and 1
print(np.random.randint(5,15))  # any random no. between 5 and 15
print(np.random.randint(5,50,15))  # 15 random no. between 5 and 50
np.random.randn(5)

[0.15219389 0.94346878 0.42708139 0.85254757 0.50908607 0.8669192
 0.40794336 0.76594064 0.44000665 0.28942093]
12
[ 7 43  5  7 17 10 10 27 44 44 38 38 43 38 13]

array([ 1.21475041,  0.47724254,  0.58224877,  0.63432892, -0.25944335])

# **Pandas**

# Series

In [16]:
import pandas as pd

In [17]:
# series creation
x1 = [4,8,4,3,2]
x1 = pd.Series(x1)
x1

0    4
1    8
2    4
3    3
4    2
dtype: int64

In [18]:
# labeling series
x1 = [4,8,4,3,2]
s1 = pd.Series(x1, index = ['I','II','III','IV','V'])
s1

I      4
II     8
III    4
IV     3
V      2
dtype: int64

In [19]:
# index based extraction
s1.iloc[2]

np.int64(4)

In [20]:
# label based extraction
s1.loc['III']

np.int64(4)

In [21]:
print(s1)
print(s1.iloc[[1,3]])   # index based extraction of multiple values
print(s1.loc[['II','IV']])  # label based extraction of multiple values

I      4
II     8
III    4
IV     3
V      2
dtype: int64
II    8
IV    3
dtype: int64
II    8
IV    3
dtype: int64

In [22]:
# labeling can contain duplicate labels
s2 = pd.Series([1,2,3,4,5],index=['A','A','B','A','B'])
print(s2,end="\n\n")

print(s2.iloc[3],end="\n\n")

print(s2.loc['A'],end="\n\n")

print(s2.loc[['A','B']])

A    1
A    2
B    3
A    4
B    5
dtype: int64

4

A    1
A    2
A    4
dtype: int64

A    1
A    2
A    4
B    3
B    5
dtype: int64

In [23]:
# merging or concatinating two series
print(s1,end="\n\n")

s3 = pd.Series([3,9],index=['VI',"VII"])
print(s3,end="\n\n")

s1 = pd.concat([s1,s3])
print(s1)
len(s1)

I      4
II     8
III    4
IV     3
V      2
dtype: int64

VI     3
VII    9
dtype: int64

I      4
II     8
III    4
IV     3
V      2
VI     3
VII    9
dtype: int64

7

In [24]:
print(s1.iloc[4])
s1.iloc[4]=9          # modify value based on index
print(s1,end="\n\n")

print(s1.loc['V'])
s1.loc['V']=11        # modify value based on label
print(s1)

2
I      4
II     8
III    4
IV     3
V      9
VI     3
VII    9
dtype: int64

9
I       4
II      8
III     4
IV      3
V      11
VI      3
VII     9
dtype: int64

In [25]:
# modification on duplicate labels
print(s2,end='\n\n')
s2.loc['A']=4
print(s2,end='\n\n')
s2.iloc[1]=8
print(s2,end='\n\n')

A    1
A    2
B    3
A    4
B    5
dtype: int64

A    4
A    4
B    3
A    4
B    5
dtype: int64

A    4
A    8
B    3
A    4
B    5
dtype: int64

In [26]:
# deleting values from series with help of labels
s1 = s1.drop(['V'])         # droped vale at label V
print(s1,end='\n\n')
s1 = s1.drop(['VI','VII'])  # droped value with multiple label
print(s1,end='\n\n')

I      4
II     8
III    4
IV     3
VI     3
VII    9
dtype: int64

I      4
II     8
III    4
IV     3
dtype: int64

In [27]:
# deleting values from series with help of index
print(s1,end='\n\n')
print(s1.drop(s1.index[2]))
print(s1,end='\n\n')
print(s1.drop(s1.index[[1,2]]))
print(s1,end='\n\n')

I      4
II     8
III    4
IV     3
dtype: int64

I     4
II    8
IV    3
dtype: int64
I      4
II     8
III    4
IV     3
dtype: int64

I     4
IV    3
dtype: int64
I      4
II     8
III    4
IV     3
dtype: int64

In [28]:
s4 = pd.Series([2,3,2,2,4,4,3,4,4,4,5,5,2,4,5])
s5=s4.value_counts()    # counts the count of number and will display in descending order of values
print(s5,end='\n\n')
print(s5.loc[2],end='\n\n')
print(s5.iloc[2],end='\n\n')

4    6
2    4
5    3
3    2
Name: count, dtype: int64

4

3

In [29]:
# if we dont know index and label just know values
print(s1)

print(np.where(s1==8))

print(s1.index[np.where(s1==8)[0]])

print(s1.index)

s1.iloc[np.where(s1==4)[0]]=1
s1.loc[s1.index[np.where(s1==8)[0]]]=10
s1.loc[s1.index[np.where(s1==3)]]=10
print(s1)

I      4
II     8
III    4
IV     3
dtype: int64
(array([1]),)
Index(['II'], dtype='object')
Index(['I', 'II', 'III', 'IV'], dtype='object')
I       1
II     10
III     1
IV     10
dtype: int64

# DataFrame

In [30]:
# DataFrame Creation

mydata = [['A',1234,20000],['B',5678,10000],['C',1357,8000],['D',4567,30000]]
print(len(mydata),end='\n\n')
print(len(mydata[0]),end='\n\n')

mydf = pd.DataFrame(mydata)
print(mydf,end='\n\n')

mydf = pd.DataFrame(mydata,columns=['Name','AccNo','Balance'])
print(mydf,end='\n\n')

temp = pd.DataFrame(mydata,columns=['Name','AccNo','Balance'],index=['Sujal','Chaitu','Omkie','Deva'])
print(temp,end='\n\n')

4

3

   0     1      2
0  A  1234  20000
1  B  5678  10000
2  C  1357   8000
3  D  4567  30000

  Name  AccNo  Balance
0    A   1234    20000
1    B   5678    10000
2    C   1357     8000
3    D   4567    30000

       Name  AccNo  Balance
Sujal     A   1234    20000
Chaitu    B   5678    10000
Omkie     C   1357     8000
Deva      D   4567    30000

In [31]:
print(mydf,end='\n\n')

print(mydf.iloc[[1,2]],end='\n\n')

print(mydf.loc[[1,2]],end='\n\n')

df1 = mydf.iloc[[1,2]]                        # it carry forwards the same label
print(df1,end='\n\n')
print(df1.iloc[1],end='\n\n')
print(df1.loc[1],end='\n\n')

df1 = mydf.iloc[[1,2]].reset_index(drop=True) # it will not carry forward the same label
print(df1,end='\n\n')

df1 = mydf.iloc[[1,2]].reset_index()  # if we dont mention drop=True then index column will be added
print(df1,end='\n\n')

  Name  AccNo  Balance
0    A   1234    20000
1    B   5678    10000
2    C   1357     8000
3    D   4567    30000

  Name  AccNo  Balance
1    B   5678    10000
2    C   1357     8000

  Name  AccNo  Balance
1    B   5678    10000
2    C   1357     8000

  Name  AccNo  Balance
1    B   5678    10000
2    C   1357     8000

Name          C
AccNo      1357
Balance    8000
Name: 2, dtype: object

Name           B
AccNo       5678
Balance    10000
Name: 1, dtype: object

  Name  AccNo  Balance
0    B   5678    10000
1    C   1357     8000

   index Name  AccNo  Balance
0      1    B   5678    10000
1      2    C   1357     8000

In [32]:
# DataFrame creation from dictionary
stu_df = {"Name":['A','B','C','D'],"RollNo":[1,2,3,4],"Marks":[50,60,75,64]}

df1 = pd.DataFrame(stu_df)
print(df1,end='\n\n')

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     64

In [36]:
# adding rows into df
print(df1,end='\n\n')

newdf = pd.DataFrame([['E',7,80],['F',10,65]],columns=df1.columns)  # for adding we should have same column names.
print(newdf,end='\n\n')

df2 = pd.concat([df1,newdf]).reset_index(drop=True)
print(df2,end='\n\n')

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     64

  Name  RollNo  Marks
0    E       7     80
1    F      10     65

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     64
4    E       7     80
5    F      10     65

In [37]:
# adding new column to df
x1 = [67,89,75,62,59,82]
df2['Marks2']=x1
print(df2,end='\n\n')

  Name  RollNo  Marks  Marks2
0    A       1     50      67
1    B       2     60      89
2    C       3     75      75
3    D       4     64      62
4    E       7     80      59
5    F      10     65      82

In [45]:
# to get shape of df
print(df2.shape)
print(df2.shape[0]) # no. of rows
print(df2.shape[1]) # no. of cols

(6, 4)
6
4

In [50]:
# accessing or modyfying perticular value use df.at[] -> at works same like loc i.e uses labels
df2.at[3,"Marks"]
df2.at[3,"Marks"] = 74
print(df2)

  Name  RollNo  Marks  Marks2
0    A       1     50      67
1    B       2     60      89
2    C       3     75      75
3    D       4     74      62
4    E       7     80      59
5    F      10     65      82

In [52]:
# df.iat[] -> it is similar to iloc[]
print(df2.iat[1,3])
print(df2.iloc[1,3])

89
89

In [54]:
# extracting or accesing complete row
print(df2.iloc[[0,3,5]],end='\n\n') # the labels were carry forwarded so use reset_index

df3 = df2.iloc[[0,3,5]].reset_index(drop=True)
print(df3,end='\n\n')

  Name  RollNo  Marks  Marks2
0    A       1     50      67
3    D       4     74      62
5    F      10     65      82

  Name  RollNo  Marks  Marks2
0    A       1     50      67
1    D       4     74      62
2    F      10     65      82

In [59]:
# extracting or accesing complete column
mySubject = df2[['Name','Marks']]   # extract using column name
print(mySubject,end='\n\n')

print(df2.iloc[:,[1,2]],end='\n\n') # extract using column index

print(df2['Marks'])
print(df2.Marks)    # we can also extract single column like this if column name does not have space

  Name  Marks
0    A     50
1    B     60
2    C     75
3    D     74
4    E     80
5    F     65

   RollNo  Marks
0       1     50
1       2     60
2       3     75
3       4     74
4       7     80
5      10     65

0    50
1    60
2    75
3    74
4    80
5    65
Name: Marks, dtype: int64
0    50
1    60
2    75
3    74
4    80
5    65
Name: Marks, dtype: int64

In [69]:
# removing rows from df
print(df2.drop([1],axis=0),end='\n\n')
print(df2.drop([2,4],axis=0) )

  Name  RollNo  Marks  Marks2
0    A       1     50      67
2    C       3     75      75
3    D       4     74      62
4    E       7     80      59
5    F      10     65      82

  Name  RollNo  Marks  Marks2
0    A       1     50      67
1    B       2     60      89
3    D       4     74      62
5    F      10     65      82

In [68]:
# removing cols from df
print(df2.drop('Marks2',axis=1), end='\n\n' )
print(df2.drop(['RollNo','Marks'],axis=1), end='\n\n' )

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     74
4    E       7     80
5    F      10     65

  Name  Marks2
0    A      67
1    B      89
2    C      75
3    D      62
4    E      59
5    F      82

In [77]:
import os
os.getcwd()

'/content/drive/MyDrive/CDAC'

In [78]:
os.chdir('/content/drive/MyDrive/CDAC')
os.getcwd()

'/content/drive/MyDrive/CDAC'

In [84]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='ERPData')
print(df,end='\n\n')

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [85]:
print(df.head(),end='\n\n')
print(df.tail(),end='\n\n')

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

   MaterialID Location  Quantity
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39