<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

from scipy.stats import chisquare

from scipy.stats import chi2_contingency

In [3]:
zoo = [34,43,57,40,85,68,67,53,41,24,42,52]
supp=[1,1,1,1,2,2,2,2,3,3,3,3]
lake=["R","D","R","D","R","D","R","D","R","D","R","D"]

In [6]:
df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})
model = ols('Resp~Factor1+Factor2',df).fit()
res1=sm.stats.anova_lm(model)
res1

           df       sum_sq     mean_sq         F    PR(>F)
Factor2   1.0   176.333333  176.333333  0.543765  0.479659
Factor1   1.0    28.125000   28.125000  0.086730  0.775056
Residual  9.0  2918.541667  324.282407       NaN       NaN

**'Resp~Factor1*Factor2'**

by using astrick between factors output table will display interaction.

In [7]:
df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})
model = ols('Resp~Factor1*Factor2',df).fit()
res=sm.stats.anova_lm(model)
res

                  df       sum_sq     mean_sq         F    PR(>F)
Factor2          1.0   176.333333  176.333333  0.483367  0.506590
Factor1          1.0    28.125000   28.125000  0.077097  0.788312
Factor1:Factor2  1.0     0.125000    0.125000  0.000343  0.985685
Residual         8.0  2918.416667  364.802083       NaN       NaN

                  df       sum_sq     mean_sq         F    PR(>F)
Factor2          1.0   176.333333  176.333333  0.483367  0.506590
Factor1          1.0    28.125000   28.125000  0.077097  0.788312
Factor1:Factor2  1.0     0.125000    0.125000  0.000343  0.985685
Residual         8.0  2918.416667  364.802083       NaN       NaN

# **One proportion test**

In [8]:
# sample is 500 and probability is 0.7
mu = 500*0.7  # n*p
sd = (500*0.7*(1-0.7))**0.5
print(mu)
print(sd)

350.0
10.2469507659596

In [9]:
binom.cdf(370,500,0.7) - binom.cdf(329,500,0.7)

np.float64(0.9547133734363867)

In [10]:
norm.cdf(370,mu,sd) - norm.cdf(329,mu,sd)

np.float64(0.954307041847664)

In [13]:
import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

**Q. suppose claim is this batch has max 40% students coming from maharashtra**

H0 pr <= 0.4
Ha pr > 0.4

In [12]:
# In a sample of 400 students , 180 students are from MH
180/400

0.45

In [15]:
statsmodels.stats.proportion.proportions_ztest(180,400,0.4,alternative='larger')
# p-value --> 0.022211592425003045
# z --> 2.0100756305184238

(np.float64(2.0100756305184238), np.float64(0.022211592425003045))

In [16]:
norm.cdf(2.0100756305184238)

np.float64(0.977788407574997)

In [17]:
1 - norm.cdf(2.0100756305184238)    # because we have  to check on right side

np.float64(0.022211592425003035)

# **2-proportion test**

**Q. Pune CDAC claims that they have atleast 8% more  engineers as compared to CDAC kharghar**

H0 pr(Pune) - pr(Kharghar) >= 0.08

Ha pr(Pune) - pr(Kharghar) < 0.08

In [18]:
# In a sample of 70 students in pune, 40 are Btechs
# In a sample of 80 students in Kharghar, 48 were Btechs
40/70 - 48/80

-0.02857142857142858

In [21]:
engg = np.array([40,48])
total = np.array([70,80])
statsmodels.stats.proportion.proportions_ztest(engg,total,0.08,alternative='smaller')

(np.float64(-1.3471563869719667), np.float64(0.08896493545619544))

# **Chi-Square test for goodness of fit**

Q. claimed pattern for the qualifiication

Btech - 0.4, Mtech - 0.1, MCA - 0.3, Msc - 0.2

Btech - 50, Mtech - 20, MCA - 45, Msc - 25

whether counts obtained from sampole follow the pattern or not

In [27]:
from scipy.stats import chisquare

In [23]:
counts = np.array([50,20,45,25])
pattern = np.array([0.4,0.1,0.3,0.2])

In [24]:
# if pattern was followed what is expected counnt
exp_counts = sum(counts) * pattern
exp_counts

array([56., 14., 42., 28.])

In [26]:
scipy.stats.chisquare(counts,f_exp=exp_counts)
# H0 do not rejected

Power_divergenceResult(statistic=np.float64(3.7500000000000004), pvalue=np.float64(0.2897557811933843))

In [29]:
counts = np.array([70,10,35,45])
pattern = np.array([0.4,0.1,0.3,0.2])
exp_counts = sum(counts) * pattern
print(exp_counts)
scipy.stats.chisquare(counts,f_exp=exp_counts)
# H0 rejected

[64. 16. 48. 32.]

Power_divergenceResult(statistic=np.float64(11.614583333333334), pvalue=np.float64(0.008827096989130126))

In [30]:
sum((exp_counts-counts)**2/exp_counts)    # test statistics

np.float64(11.614583333333334)

In [31]:
(exp_counts-counts)**2/exp_counts

array([0.5625    , 2.25      , 3.52083333, 5.28125   ])

# **Chi-Square test for Degree of Association**

Eg. three foods - south,maharashtrian,gujrati

In [32]:
from scipy.stats import chi2_contingency

In [37]:
# here we will use 2d array
food = np.array([[45,70,60],[70,40,25]])
food

array([[45, 70, 60],
       [70, 40, 25]])

In [38]:
scipy.stats.chi2_contingency(food)

Chi2ContingencyResult(statistic=np.float64(23.25424258416586), pvalue=np.float64(8.920832446902749e-06), dof=2, expected_freq=array([[64.91935484, 62.09677419, 47.98387097],
       [50.08064516, 47.90322581, 37.01612903]]))