<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from numpy import random

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx',sheet_name='ERPData')

In [ ]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
x1 = np.random.randint(10,80,50)

In [ ]:
df['Value'] = x1

In [ ]:
df.head()

  MaterialID Location  Quantity  Value
0    TMI-43T    MWH-4        34     32
1    AXCP-78    MWH-1        67     55
2    LXCV-21    MWH-2        27     69
3    AXCP-78    MWH-5        65     10
4    AXCP-78    MWH-4        36     33

In [ ]:
# grouping will never be done on continuous data or discrete, it will be done on categorical data

grp1 = df.groupby('MaterialID')
grp1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [ ]:
grp1.get_group('SDRT-67')

   MaterialID Location  Quantity  Value
10    SDRT-67    MWH-1        34     31
11    SDRT-67    MWH-4        58     61
16    SDRT-67    MWH-5        12     49
17    SDRT-67    MWH-5       102     72
41    SDRT-67    MWH-1        57     66
42    SDRT-67    MWH-2        31     33

In [ ]:
grp1.Quantity.mean()

MaterialID
AXCP-78    81.636364
DDBN-89    47.875000
GCVB-79    36.400000
LXCV-21    48.600000
SDRT-67    49.000000
TMI-43T    59.000000
Name: Quantity, dtype: float64

In [ ]:
grp1.Quantity.agg(np.mean)

/tmp/ipykernel_766/719844975.py:1: FutureWarning: The provided callable <function mean at 0x7e0398135940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp1.Quantity.agg(np.mean)

MaterialID
AXCP-78    81.636364
DDBN-89    47.875000
GCVB-79    36.400000
LXCV-21    48.600000
SDRT-67    49.000000
TMI-43T    59.000000
Name: Quantity, dtype: float64

In [ ]:
grp1.Quantity.agg(np.size)

MaterialID
AXCP-78    11
DDBN-89     8
GCVB-79     5
LXCV-21     5
SDRT-67     6
TMI-43T    15
Name: Quantity, dtype: int64

In [ ]:
grp1.Quantity.agg([np.size,np.sum,np.mean])

/tmp/ipykernel_766/58817162.py:1: FutureWarning: The provided callable <function sum at 0x7e0398134860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1.Quantity.agg([np.size,np.sum,np.mean])
/tmp/ipykernel_766/58817162.py:1: FutureWarning: The provided callable <function mean at 0x7e0398135940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp1.Quantity.agg([np.size,np.sum,np.mean])

            size  sum       mean
MaterialID
AXCP-78       11  898  81.636364
DDBN-89        8  383  47.875000
GCVB-79        5  182  36.400000
LXCV-21        5  243  48.600000
SDRT-67        6  294  49.000000
TMI-43T       15  885  59.000000

In [ ]:
grp1.Quantity.agg(['size','sum','mean'])

            size  sum       mean
MaterialID
AXCP-78       11  898  81.636364
DDBN-89        8  383  47.875000
GCVB-79        5  182  36.400000
LXCV-21        5  243  48.600000
SDRT-67        6  294  49.000000
TMI-43T       15  885  59.000000

In [ ]:
s1 = grp1.Quantity.agg(np.size)
d1 = pd.DataFrame(s1)
d1

            Quantity
MaterialID
AXCP-78           11
DDBN-89            8
GCVB-79            5
LXCV-21            5
SDRT-67            6
TMI-43T           15

In [ ]:
d1.loc['SDRT-67']

Quantity    6
Name: SDRT-67, dtype: int64

In [ ]:
print(d1.index)
np.where(d1.index=='SDRT-67')

Index(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'], dtype='object', name='MaterialID')

(array([4]),)

In [ ]:
d1.iloc[np.where(d1.index=='SDRT-67')]

            Quantity
MaterialID
SDRT-67            6

In [ ]:
d2 = grp1.Quantity.agg([np.size,np.sum,np.mean])
d2

/tmp/ipykernel_766/1435843678.py:1: FutureWarning: The provided callable <function sum at 0x7e0398134860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  d2 = grp1.Quantity.agg([np.size,np.sum,np.mean])
/tmp/ipykernel_766/1435843678.py:1: FutureWarning: The provided callable <function mean at 0x7e0398135940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  d2 = grp1.Quantity.agg([np.size,np.sum,np.mean])

            size  sum       mean
MaterialID
AXCP-78       11  898  81.636364
DDBN-89        8  383  47.875000
GCVB-79        5  182  36.400000
LXCV-21        5  243  48.600000
SDRT-67        6  294  49.000000
TMI-43T       15  885  59.000000

In [ ]:
print(d2.loc['SDRT-67','sum'])
print(d2.iloc[4,1])

294
294

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx",sheet_name='Health')
df

   Country       Disease  2019  2020  2021
0    India        Cancer    12    94    35
1       UK        Cancer    95    19    84
2       US        Cancer    98    19    53
3    Japan        Cancer    89    52    14
4    India         Covid    38    19    62
5       UK         Covid    69    73    35
6       US         Covid    87    97    35
7    Japan         Covid    14    12    90
8    India  Heart Attack    84    10    98
9       UK  Heart Attack    44    17    24
10      US  Heart Attack    34    40    54
11   Japan  Heart Attack    11    43    75

In [ ]:
# broad long - no. of rows gets increased   -> melt()
# broad wide - no. of columns gets increased    -> pivot_table()

df1 = df.melt(id_vars=['Country','Disease'],var_name='Year',value_name='Cases')
df1.head()

# the columns which we didnt want to mofify or update are in id_vars=[]
# the columns which we have to be update are mentioned in var_name='' and value_name=''.

  Country Disease  Year  Cases
0   India  Cancer  2019     12
1      UK  Cancer  2019     95
2      US  Cancer  2019     98
3   Japan  Cancer  2019     89
4   India   Covid  2019     38

In [ ]:
print(df.shape)
print(df1.shape)    # Here broad long takes place

(12, 5)
(36, 4)

In [ ]:
df2 = df1.pivot_table(values='Cases',index=['Country','Year'],columns='Disease')  # here we have multiindexes
df2

Disease       Cancer  Covid  Heart Attack
Country Year
India   2019    12.0   38.0          84.0
        2020    94.0   19.0          10.0
        2021    35.0   62.0          98.0
Japan   2019    89.0   14.0          11.0
        2020    52.0   12.0          43.0
        2021    14.0   90.0          75.0
UK      2019    95.0   69.0          44.0
        2020    19.0   73.0          17.0
        2021    84.0   35.0          24.0
US      2019    98.0   87.0          34.0
        2020    19.0   97.0          40.0
        2021    53.0   35.0          54.0

In [ ]:
df3 = df1.pivot_table(values='Cases',index='Country',columns=['Disease','Year'])
df3

Disease Cancer             Covid             Heart Attack
Year      2019  2020  2021  2019  2020  2021         2019  2020  2021
Country
India     12.0  94.0  35.0  38.0  19.0  62.0         84.0  10.0  98.0
Japan     89.0  52.0  14.0  14.0  12.0  90.0         11.0  43.0  75.0
UK        95.0  19.0  84.0  69.0  73.0  35.0         44.0  17.0  24.0
US        98.0  19.0  53.0  87.0  97.0  35.0         34.0  40.0  54.0

In [ ]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(36, 4)
(12, 3)
(4, 9)

In [ ]:
print(df2.index)
print(df2.columns)

MultiIndex([('India', 2019),
            ('India', 2020),
            ('India', 2021),
            ('Japan', 2019),
            ('Japan', 2020),
            ('Japan', 2021),
            (   'UK', 2019),
            (   'UK', 2020),
            (   'UK', 2021),
            (   'US', 2019),
            (   'US', 2020),
            (   'US', 2021)],
           names=['Country', 'Year'])
Index(['Cancer', 'Covid', 'Heart Attack'], dtype='object', name='Disease')

In [ ]:
df2 = df1.pivot_table(values='Cases',index=['Country','Year'],columns='Disease').reset_index()    # removed multiindex
df2

Disease Country  Year  Cancer  Covid  Heart Attack
0         India  2019    12.0   38.0          84.0
1         India  2020    94.0   19.0          10.0
2         India  2021    35.0   62.0          98.0
3         Japan  2019    89.0   14.0          11.0
4         Japan  2020    52.0   12.0          43.0
5         Japan  2021    14.0   90.0          75.0
6            UK  2019    95.0   69.0          44.0
7            UK  2020    19.0   73.0          17.0
8            UK  2021    84.0   35.0          24.0
9            US  2019    98.0   87.0          34.0
10           US  2020    19.0   97.0          40.0
11           US  2021    53.0   35.0          54.0

In [ ]:
df2 = df1.pivot_table(values='Cases',index=['Country','Year'],columns='Disease').reset_index().rename_axis(columns=None)    # removed index column name
df2

   Country  Year  Cancer  Covid  Heart Attack
0    India  2019    12.0   38.0          84.0
1    India  2020    94.0   19.0          10.0
2    India  2021    35.0   62.0          98.0
3    Japan  2019    89.0   14.0          11.0
4    Japan  2020    52.0   12.0          43.0
5    Japan  2021    14.0   90.0          75.0
6       UK  2019    95.0   69.0          44.0
7       UK  2020    19.0   73.0          17.0
8       UK  2021    84.0   35.0          24.0
9       US  2019    98.0   87.0          34.0
10      US  2020    19.0   97.0          40.0
11      US  2021    53.0   35.0          54.0

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx",sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
df1 = df.pivot_table(values='Quantity',index=['MaterialID'],columns='Location')
df1

Location         MWH-1  MWH-2  MWH-3      MWH-4       MWH-5
MaterialID
AXCP-78     109.600000   85.0   29.0  36.000000   66.666667
DDBN-89      43.333333   69.0   38.0  37.500000   71.000000
GCVB-79            NaN   39.0    NaN        NaN   26.000000
LXCV-21            NaN   27.0   42.0        NaN   58.000000
SDRT-67      45.500000   31.0    NaN  58.000000   57.000000
TMI-43T     120.000000   29.0   65.0  50.818182  112.000000

In [ ]:
df1 = df.pivot_table(values='Quantity',index=['MaterialID'],columns='Location',aggfunc='mean')
df1

Location         MWH-1  MWH-2  MWH-3      MWH-4       MWH-5
MaterialID
AXCP-78     109.600000   85.0   29.0  36.000000   66.666667
DDBN-89      43.333333   69.0   38.0  37.500000   71.000000
GCVB-79            NaN   39.0    NaN        NaN   26.000000
LXCV-21            NaN   27.0   42.0        NaN   58.000000
SDRT-67      45.500000   31.0    NaN  58.000000   57.000000
TMI-43T     120.000000   29.0   65.0  50.818182  112.000000

In [ ]:
df1 = df.pivot_table(values='Quantity',index='MaterialID',columns='Location',aggfunc='sum')
df1

Location    MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID
AXCP-78     548.0   85.0   29.0   36.0  200.0
DDBN-89     130.0   69.0   38.0   75.0   71.0
GCVB-79       NaN  156.0    NaN    NaN   26.0
LXCV-21       NaN   27.0   42.0    NaN  174.0
SDRT-67      91.0   31.0    NaN   58.0  114.0
TMI-43T     120.0   29.0   65.0  559.0  112.0

In [ ]:
df1 = df.pivot_table(values='Quantity',index='MaterialID',columns='Location',aggfunc='size')
df1

Location    MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID
AXCP-78       5.0    1.0    1.0    1.0    3.0
DDBN-89       3.0    1.0    1.0    2.0    1.0
GCVB-79       NaN    4.0    NaN    NaN    1.0
LXCV-21       NaN    1.0    1.0    NaN    3.0
SDRT-67       2.0    1.0    NaN    1.0    2.0
TMI-43T       1.0    1.0    1.0   11.0    1.0

In [ ]:
df1 = df.pivot_table(values='Quantity',index='MaterialID',columns='Location',aggfunc=['mean','sum','size'])
df1

                  mean                                       sum               \
Location         MWH-1 MWH-2 MWH-3      MWH-4       MWH-5  MWH-1  MWH-2 MWH-3
MaterialID
AXCP-78     109.600000  85.0  29.0  36.000000   66.666667  548.0   85.0  29.0
DDBN-89      43.333333  69.0  38.0  37.500000   71.000000  130.0   69.0  38.0
GCVB-79            NaN  39.0   NaN        NaN   26.000000    NaN  156.0   NaN
LXCV-21            NaN  27.0  42.0        NaN   58.000000    NaN   27.0  42.0
SDRT-67      45.500000  31.0   NaN  58.000000   57.000000   91.0   31.0   NaN
TMI-43T     120.000000  29.0  65.0  50.818182  112.000000  120.0   29.0  65.0

                          size
Location    MWH-4  MWH-5 MWH-1 MWH-2 MWH-3 MWH-4 MWH-5
MaterialID
AXCP-78      36.0  200.0   5.0   1.0   1.0   1.0   3.0
DDBN-89      75.0   71.0   3.0   1.0   1.0   2.0   1.0
GCVB-79       NaN   26.0   NaN   4.0   NaN   NaN   1.0
LXCV-21       NaN  174.0   NaN   1.0   1.0   NaN   3.0
SDRT-67      58.0  114.0   2.0   1.0   NaN   1.0   2.0
TMI-43T     559.0  112.0   1.0   1.0   1.0  11.0   1.0

In [ ]:
df1 = df.pivot_table(values='Quantity',index=['MaterialID','Location'],columns='Location',aggfunc=['size'])
df1

                     size
Location            MWH-1 MWH-2 MWH-3 MWH-4 MWH-5
MaterialID Location
AXCP-78    MWH-1      5.0   NaN   NaN   NaN   NaN
           MWH-2      NaN   1.0   NaN   NaN   NaN
           MWH-3      NaN   NaN   1.0   NaN   NaN
           MWH-4      NaN   NaN   NaN   1.0   NaN
           MWH-5      NaN   NaN   NaN   NaN   3.0
DDBN-89    MWH-1      3.0   NaN   NaN   NaN   NaN
           MWH-2      NaN   1.0   NaN   NaN   NaN
           MWH-3      NaN   NaN   1.0   NaN   NaN
           MWH-4      NaN   NaN   NaN   2.0   NaN
           MWH-5      NaN   NaN   NaN   NaN   1.0
GCVB-79    MWH-2      NaN   4.0   NaN   NaN   NaN
           MWH-5      NaN   NaN   NaN   NaN   1.0
LXCV-21    MWH-2      NaN   1.0   NaN   NaN   NaN
           MWH-3      NaN   NaN   1.0   NaN   NaN
           MWH-5      NaN   NaN   NaN   NaN   3.0
SDRT-67    MWH-1      2.0   NaN   NaN   NaN   NaN
           MWH-2      NaN   1.0   NaN   NaN   NaN
           MWH-4      NaN   NaN   NaN   1.0   NaN
           MWH-5      NaN   NaN   NaN   NaN   2.0
TMI-43T    MWH-1      1.0   NaN   NaN   NaN   NaN
           MWH-2      NaN   1.0   NaN   NaN   NaN
           MWH-3      NaN   NaN   1.0   NaN   NaN
           MWH-4      NaN   NaN   NaN  11.0   NaN
           MWH-5      NaN   NaN   NaN   NaN   1.0

In [ ]:
df1.loc['AXCP-78']

          size
Location MWH-1 MWH-2 MWH-3 MWH-4 MWH-5
Location
MWH-1      5.0   NaN   NaN   NaN   NaN
MWH-2      NaN   1.0   NaN   NaN   NaN
MWH-3      NaN   NaN   1.0   NaN   NaN
MWH-4      NaN   NaN   NaN   1.0   NaN
MWH-5      NaN   NaN   NaN   NaN   3.0

In [ ]:
df1.xs('MWH-1',level=1)

            size
Location   MWH-1 MWH-2 MWH-3 MWH-4 MWH-5
MaterialID
AXCP-78      5.0   NaN   NaN   NaN   NaN
DDBN-89      3.0   NaN   NaN   NaN   NaN
SDRT-67      2.0   NaN   NaN   NaN   NaN
TMI-43T      1.0   NaN   NaN   NaN   NaN

### **Statistics**

## **Types of data**
**Qualitative / Categorical / Attribute data:** will be mostly in words (ex: name,state)   
**Quantitative data:** will be in numbers (ex: age,marks)

**Quantitative Parts :**                                                           
**Continuous data ->** bold text Continuous data is the one where possibility of decimal  point cannot be ruled out
*   it will always a result of measurement
*   it will  always be expressed as mlt

**Discrete data ->** will never have decimal point
*   it will always be a result of counting and will never have decimal point


**when n*p and n*(1-p) > 10 then discrete data can be considered as Continuous. (n = sample size)**
**Any rating or ranking number in categorical data**

## **Types of Scale**
1. Nominal : answer will not change if we change logical order . Categories with no logical order
2. Ordinal : answer will change if we change logical order. Categories have logical order - ranting/ranking
3. Interval : 0 does not mean absence of measurement so mathematical operations will be restricted. (ex: temperature). We can do comparision but we cannot take ratios in interval scale.
4. Ratio : used for both count and discrete

-- When type of data is categorical then type of scale will be either Nominal or Ordinal
--


ration : division of two continuous values

proportion : division of two discrete values