<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd
from numpy import random

In [11]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx',sheet_name='ERPData')

In [12]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [13]:
x1 = np.random.randint(10,80,50)

In [14]:
df['Value'] = x1

In [15]:
df.head()

  MaterialID Location  Quantity  Value
0    TMI-43T    MWH-4        34     32
1    AXCP-78    MWH-1        67     55
2    LXCV-21    MWH-2        27     69
3    AXCP-78    MWH-5        65     10
4    AXCP-78    MWH-4        36     33

In [17]:
# grouping will never be done on continuous data or discrete, it will be done on categorical data

grp1 = df.groupby('MaterialID')
grp1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [18]:
grp1.get_group('SDRT-67')

   MaterialID Location  Quantity  Value
10    SDRT-67    MWH-1        34     31
11    SDRT-67    MWH-4        58     61
16    SDRT-67    MWH-5        12     49
17    SDRT-67    MWH-5       102     72
41    SDRT-67    MWH-1        57     66
42    SDRT-67    MWH-2        31     33

In [19]:
grp1.Quantity.mean()

MaterialID
AXCP-78    81.636364
DDBN-89    47.875000
GCVB-79    36.400000
LXCV-21    48.600000
SDRT-67    49.000000
TMI-43T    59.000000
Name: Quantity, dtype: float64

In [20]:
grp1.Quantity.agg(np.mean)

/tmp/ipykernel_766/719844975.py:1: FutureWarning: The provided callable <function mean at 0x7e0398135940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp1.Quantity.agg(np.mean)

MaterialID
AXCP-78    81.636364
DDBN-89    47.875000
GCVB-79    36.400000
LXCV-21    48.600000
SDRT-67    49.000000
TMI-43T    59.000000
Name: Quantity, dtype: float64

In [21]:
grp1.Quantity.agg(np.size)

MaterialID
AXCP-78    11
DDBN-89     8
GCVB-79     5
LXCV-21     5
SDRT-67     6
TMI-43T    15
Name: Quantity, dtype: int64

In [23]:
grp1.Quantity.agg([np.size,np.sum,np.mean])

/tmp/ipykernel_766/58817162.py:1: FutureWarning: The provided callable <function sum at 0x7e0398134860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1.Quantity.agg([np.size,np.sum,np.mean])
/tmp/ipykernel_766/58817162.py:1: FutureWarning: The provided callable <function mean at 0x7e0398135940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp1.Quantity.agg([np.size,np.sum,np.mean])

            size  sum       mean
MaterialID
AXCP-78       11  898  81.636364
DDBN-89        8  383  47.875000
GCVB-79        5  182  36.400000
LXCV-21        5  243  48.600000
SDRT-67        6  294  49.000000
TMI-43T       15  885  59.000000

In [24]:
grp1.Quantity.agg(['size','sum','mean'])

            size  sum       mean
MaterialID
AXCP-78       11  898  81.636364
DDBN-89        8  383  47.875000
GCVB-79        5  182  36.400000
LXCV-21        5  243  48.600000
SDRT-67        6  294  49.000000
TMI-43T       15  885  59.000000

In [31]:
s1 = grp1.Quantity.agg(np.size)
d1 = pd.DataFrame(s1)
d1

            Quantity
MaterialID
AXCP-78           11
DDBN-89            8
GCVB-79            5
LXCV-21            5
SDRT-67            6
TMI-43T           15

In [32]:
d1.loc['SDRT-67']

Quantity    6
Name: SDRT-67, dtype: int64

In [39]:
print(d1.index)
np.where(d1.index=='SDRT-67')

Index(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'], dtype='object', name='MaterialID')

(array([4]),)

In [40]:
d1.iloc[np.where(d1.index=='SDRT-67')]

            Quantity
MaterialID
SDRT-67            6

In [41]:
d2 = grp1.Quantity.agg([np.size,np.sum,np.mean])
d2

/tmp/ipykernel_766/1435843678.py:1: FutureWarning: The provided callable <function sum at 0x7e0398134860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  d2 = grp1.Quantity.agg([np.size,np.sum,np.mean])
/tmp/ipykernel_766/1435843678.py:1: FutureWarning: The provided callable <function mean at 0x7e0398135940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  d2 = grp1.Quantity.agg([np.size,np.sum,np.mean])

            size  sum       mean
MaterialID
AXCP-78       11  898  81.636364
DDBN-89        8  383  47.875000
GCVB-79        5  182  36.400000
LXCV-21        5  243  48.600000
SDRT-67        6  294  49.000000
TMI-43T       15  885  59.000000

In [44]:
print(d2.loc['SDRT-67','sum'])
print(d2.iloc[4,1])

294
294